name: build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:3.6
        ports:
          - 27017:27017

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1.4.3
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Compile typescript
        run: npm run tsc
      - name: Run unit tests
        run: npm test
