name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:3.6
        ports:
          - 27017:27017

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Compile typescript
        run: npm run tsc
      - name: Run unit tests
        run: npm test
      - name: Ensure no change
        run: git diff-index --quiet HEAD
